version: '3'

services:
  find-a-friend-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=123
      - POSTGRESQL_DATABASE=find_a_friend
    container_name: find-a-friend-container
